baseURL: "https://untidyramblings.com"
languageCode: en-us"
title: untidyramblings
theme: 'base'

menu:
  nav:
  - name: Words
    url: /words/
    weight: 1
  - name: About
    url: /about/
    weight: 4

taxonomies:
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
